backend:
  name: github
  repo: hsa29568-dot/my-shop
  branch: main

media_folder: "image"
public_folder: "/image"

collections:
  - name: "products"
    label: "All Products"
    files:
      - label: "Product List"
        name: "product_list"
        file: "products.json"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Price", name: "price", widget: "number" }
              - { label: "Image", name: "image", widget: "image" }