backend:
  name: git-gateway
  branch: main

media_folder: "image"
public_folder: "/image"

collections:
  - name: "products"
    label: "Products"
    folder: "/"
    extension: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Product Image", name: "image", widget: "image" }